import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// POST /api/invites — send invite email
export async function POST(req: NextRequest) {
  try {
    const { workspace_id, workspace_name, email, role, invited_by, inviter_name } = await req.json()

    if (!workspace_id || !email || !invited_by) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    // Check not already a member
    const { data: existing } = await supabase
      .from('workspace_members')
      .select('id')
      .eq('workspace_id', workspace_id)
      .eq('email', email)

    if (existing && existing.length > 0) {
      return NextResponse.json({ error: 'User is already a member' }, { status: 400 })
    }

    // Check for existing pending invite
    const { data: existingInvite } = await supabase
      .from('workspace_invites')
      .select('id')
      .eq('workspace_id', workspace_id)
      .eq('email', email)
      .eq('accepted', false)

    if (existingInvite && existingInvite.length > 0) {
      return NextResponse.json({ error: 'Invite already sent to this email' }, { status: 400 })
    }

    // Create invite row (token auto-generated by DB)
    const { data: invite, error: inviteErr } = await supabase
      .from('workspace_invites')
      .insert({ workspace_id, email, role: role ?? 'member', invited_by })
      .select()
      .single()

    if (inviteErr || !invite) {
      return NextResponse.json({ error: 'Failed to create invite' }, { status: 500 })
    }

    const acceptUrl = `${process.env.NEXT_PUBLIC_APP_URL}/auth/accept-invite?token=${invite.token}`

    // Send email via Resend
    const resendRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'AZOTH Platform <onboarding@resend.dev>',
        to: email,
        subject: `${inviter_name ?? 'Someone'} invited you to ${workspace_name ?? 'a workspace'} on AZOTH`,
        html: `
          <div style="font-family:sans-serif;max-width:480px;margin:0 auto;padding:32px 24px;background:#0f1117;color:#e8e8e8;border-radius:12px">
            <div style="font-size:22px;font-weight:700;color:#e8a045;margin-bottom:8px">AZOTH</div>
            <h2 style="font-size:18px;font-weight:600;margin:0 0 12px">You've been invited</h2>
            <p style="color:#aaa;font-size:14px;line-height:1.6;margin:0 0 24px">
              <strong style="color:#e8e8e8">${inviter_name ?? 'A teammate'}</strong> has invited you to join
              <strong style="color:#e8e8e8">${workspace_name ?? 'a workspace'}</strong> on AZOTH as a
              <strong style="color:#e8e8e8">${role ?? 'member'}</strong>.
            </p>
            <a href="${acceptUrl}"
               style="display:inline-block;background:#e8a045;color:#000;font-weight:700;font-size:14px;padding:12px 28px;border-radius:8px;text-decoration:none">
              Accept Invite
            </a>
            <p style="color:#555;font-size:12px;margin-top:28px">
              This invite expires in 7 days. If you didn't expect this, you can ignore it.
            </p>
          </div>
        `,
      }),
    })

    if (!resendRes.ok) {
      const errBody = await resendRes.json()
      console.error('[AZOTH] Resend error:', errBody)
      return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
    }

    return NextResponse.json({ success: true, invite_id: invite.id })
  } catch (err) {
    console.error('[AZOTH] invite POST:', err)
    return NextResponse.json({ error: 'Server error' }, { status: 500 })
  }
}

// GET /api/invites?token=xxx — validate token
export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get('token')
  if (!token) return NextResponse.json({ error: 'Missing token' }, { status: 400 })

  const { data: invite, error } = await supabase
    .from('workspace_invites')
    .select('*, workspaces(name, accent, industry)')
    .eq('token', token)
    .single()

  if (error || !invite) return NextResponse.json({ error: 'Invalid invite' }, { status: 404 })
  if (invite.accepted)   return NextResponse.json({ error: 'Invite already used' }, { status: 410 })
  if (new Date(invite.expires_at) < new Date()) return NextResponse.json({ error: 'Invite expired' }, { status: 410 })

  return NextResponse.json({ invite })
}